### ISSUE TITLE
terminate called after throwing an instance of 'std::logic_error'

### ISSUE THREAD

**Issue by cihga39871** [hellosunking/Ktrim#7]
Hi,

I tried to run ktrim 1.2.1 but got the error message:

```
ktrim -1 r1.fq -2 r2.fq -t 4
terminate called after throwing an instance of 'std::logic_error'
  what():  basic_string::_M_construct null not valid
```

Do you have any clue? Thank you.

----
**System info**
Ubuntu 20.04
g++: (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
libz: /lib/x86_64-linux-gnu/libz.so.1.2.11

**Comment by hellosunking** [comment]
Hi,

You get this error because you did not provide the "-o" option which is used to specify the output files.

It is a bug that Ktrim does not check the validity of this parameter. I have fixed this bug in v1.2.2.

Thanks.
